server:
  port: 7777
spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: 'null'
    url: jdbc:h2:mem:testdb
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show-sql: true
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
      
phonebook:
    messages:
       contactSavedSuccess: Contact Saved Successfully
       contactSavedFailure: Contact Saved Failed
       contactUpdateSuccess: Contact Updated Successfully
       contactDeleteSuccess: Contact Deleted SuccessFully
       contactDeleteFailure: Contact Deleted Failed